### ISSUE TITLE
Group my Groups

### ISSUE THREAD

**Issue by KamiSamaFreak** [denschub/firefox-tabgroups#41]
The ability to Group several tab groups would be amazing.

example current:

-->Zelda

-->Spyro

-->Mariokart

-->Final Fantasy

example:

-->Games

 --> -->Zelda

--> -->Spyro

--> -->Mariokart

--> -->Final Fantasy

I hope this comes across, err this text Editor bullet-list wont make sub-bullet points.

**Comment by skyschub** [comment]
Hm. I've thought about this and honestly, I am not a fan of this idea. I'd like both the UI and the code of this extension to be as simple as possible, and nesting groups would definitely add a lot of complexity on both ends.

There are extension like [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) which should cover your use case as well.

Since I do not really see the benefit and I doubt there are a lot of people interesting in actually nesting groups, I'll close this feature request. If, for some reason, a lot of people want to have this, we can always reopen, of course.

Thanks for your contribution nonetheless!
