### ISSUE TITLE
Integrate the Tab Bar from Tab Groups Button plugin

### ISSUE THREAD

**Issue by PrototypeNM1** [denschub/firefox-tabgroups#64]
Tab Groups Button has the cleanest and simplest tab bar. It also has the clever idea of placing the group bar under the URL separating tab selection from group selection, a feature which helps you stay oriented as you never accidentally switch into another group.

As is the plugin works with Tab Groups, but not Simplified Tab Groups. Source code can be found [here](https://github.com/char101/tabgroupsbtn).

**Comment by PrototypeNM1** [comment]
I'd be interested in porting this functionality to Simplified Tab Groups, but this would be my first foray into Firefox plugins and I'm unsure what to look for wrt WebExtensions compatibility. Any direction would be appreciated.

**Comment by mikhoul** [comment]
[**@PrototypeNM1**](https://github.com/PrototypeNM1) commented on [1 juill. 2017 21 h 02 HAE](https://github.com/denschub/firefox-tabgroups/issues/64#issuecomment-312464302 "2017-07-02T01:02:38Z - Replied by Github Reply Comments"):
> I'd be interested in porting this functionality to Simplified Tab Groups, but this would be my first foray into Firefox plugins and I'm unsure what to look for wrt WebExtensions compatibility. Any direction would be appreciated.

I've just looked quickly to "TabGroups Button " and it's a XUL addon so it can't be easily ported to WebExt.

The best thing to do IMO would be to re-write it from the ground but I'm not sure at all you could ad such button with WebExt since I don't think there is an API to change the browser interface.

But overall Webext are relatively easy to learn so you maybe you will be able to customize something that fit you need.

Regards :octocat:

**Comment by PrototypeNM1** [comment]
It looks like a tab bar is blocked for the moment as WebExtensions does not currently have a [toolbar API](https://bugzilla.mozilla.org/show_bug.cgi?id=1215064).

**Comment by skyschub** [comment]
Closing this. If anything, support has to be implemented in "TabGroups Button", not here.
