### ISSUE TITLE
Session restore doesn't restore tab groups

### ISSUE THREAD

**Issue by whiskytroll** [denschub/firefox-tabgroups#76]
I exited Firefox normally (closed the window with the close button) and restarted my computer, then opened Firefox with standard settings (menu launcher). The only tab group that was visible after start up was the one that was active when closing Firefox, but it didn't retain it's name from previous session. The tab groups icon shows only the entries "Unnamed Group 1" (highlighted) and "Create new group".

I'm on Firefox 56.0(64-bit) for Linux Mint mint-1.0, at Linux Mint 18.2 Cinnamon desktop.

I have changed the setting for Simplified Tab Groups 0.5.1 to only listen to shortcut Ctrl+Shift+e.

I use Tab Mix Plus 0.5.0.4 to manage my sessions. 

Is there a way to restore the tabs end preferably the tab groups as well? I had 4 different other groups, out of which 2 were very important to me (or at least their content was), so I really hope you can help me.

Regards / Jesper

**Comment by skyschub** [comment]
The currently released extension version uses Firefox' SessionStorage to store data. If you enable session restoring in the Firefox preferences, it does what you'd expect. If you use something external, it does not. Technically, that's not even my fault, since Tab Mix Plus could restore the SessionStorage as well. In any way, the old version is unsupported, and the new is blocked by #60.

Since the WebExtension API will take care of session restore, there is nothing to do here.

**Comment by whiskytroll** [comment]
I see. Thank you for a quick reply. Perhaps you would consider to add a note in the settings or description that one should only use Firefox' native session manager? It might very well help some other poor soul.

**Comment by skyschub** [comment]
As I said earlier, the current version of this extension **is unsupported** and there **will be no further updates** to the current code. Whenever I have a WebExtension API for hiding tabs, as it is tracked in #60, I will release a new version where this limitation does not apply. So sorry, but no, I do not consider adding a note.

**Comment by whiskytroll** [comment]
I'm sorry, I didn't realize that you would have to update the code in order to add a note.

**Comment by whiskytroll** [comment]
One last note, if someone else encounters this: I've changed preferences in Tab Mix Plus to use Firefox session manager and then without restarting Firefox I've recreated the tab groups that I had prior to the loss of them. And lo and behold! When I typed the very same names to new groups as I had previously used they became repopulated with the old tabs. No tabs lost, as long as I could remember the exact names of the old groups! (I believe I also remade them in the same order as the first time, but I'm not sure. If you have the same problem and don't have a reason not to, I'd suggest you try to remake in the same order.)

**Comment by skyschub** [comment]
Yeah, I need to update sources to add a note to the settings. However, I can edit the addon listing on AMO [and so I did](https://addons.mozilla.org/en-US/firefox/addon/tab-groups/). Instead of talking about session restore, however, I added a note about general Firefox Quantum compatibility. Thanks for reminding me.
